
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\lucas\Desktop\Tkinter-Designer-master\Tkinter-Designer-master\build2\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.attributes('-fullscreen', True)
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 1080,
    width = 1920,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    960.0,
    543.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    960.0,
    112.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    960.0,
    570.0,
    image=image_image_3
)

canvas.create_text(
    1332.0,
    716.0,
    anchor="nw",
    text="Nota média ",
    fill="#F9FBC7",
    font=("Inter", 22 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    1496.0,
    741.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    1530.0,
    741.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    1564.0,
    741.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    1598.0,
    741.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    1632.0,
    741.0,
    image=image_image_8
)

canvas.create_text(
    1333.0,
    779.0,
    anchor="nw",
    text="500 horas jogadas",
    fill="#F9FBC7",
    font=("Inter", 22 * -1)
)

canvas.create_text(
    1332.0,
    831.0,
    anchor="nw",
    text="Jogado 45 vezes nos últimos 30 dias",
    fill="#F9FBC7",
    font=("Inter", 22 * -1)
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    1743.0,
    669.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    1381.0,
    669.0,
    image=image_image_10
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    1562.0,
    669.0,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    1520.0,
    531.0,
    image=image_image_12
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    1523.0,
    323.0,
    image=image_image_13
)

canvas.create_text(
    82.0,
    266.0,
    anchor="nw",
    text="Sobre",
    fill="#F9FBC7",
    font=("Inter", 44 * -1)
)

image_image_14 = PhotoImage(
    file=relative_to_assets("image_14.png"))
image_14 = canvas.create_image(
    358.0,
    349.0,
    image=image_image_14
)

canvas.create_text(
    82.0,
    349.0,
    anchor="nw",
    text="\nStardew Valley é um RPG sem fim da vida no\ncampo! Você herdou a antiga fazenda de\nseu avô no Vale do Orvalho. Equipado com\nferramentas de segunda mão e algumas\nmoedas, você irá começar sua nova vida.\nSerá que você consegue aprender a viver da\nterra e transformar esses campos\nabsurdamente vegetados em uma casa\npróspera? Não vai ser fácil. Desde que\nCorporação Joja veio à cidade, os antigos\nmodos de vida quase desapareceram. O\nCentro Comunitário, uma vez o lugar mais\nvisitado da cidade,agora está em ruínas.\nMas o vale parece cheio de oportunidades.\nCom um pouco de dedicação, você pode ser\na pessoa que restaurará a grandeza do Vale\ndo Orvalho!",
    fill="#FFFFFF",
    font=("Inter", 26 * -1)
)
window.resizable(False, False)
window.mainloop()
